version: '3.8'

services:
  pharmacy-exporter:
    image: pharmacy-exporter:latest
    build: .
    container_name: pharmacy-exporter
    restart: unless-stopped
    ports:
      - "8008:8008"
    environment:
      - SCRAPE_INTERVAL=${SCRAPE_INTERVAL:-30}  # Значение по умолчанию: 30 секунд
    volumes:
      - ./target_list.yml:/target/target_list.yml  # Монтирование конфигурации
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
